
set(CPACK_PACKAGE_NAME "bash-llvm")
set(CPACK_PACKAGE_AUTHOR "Fox Ellison-Taylor")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A bash frontend for LLVM")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "3")
set(CPACK_PACKAGE_VERSION "v${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
set(CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME}-${CPACK_PACKAGE_VERSION}-${TRIPLET}")

set(CPACK_PACKAGE_INSTALL_DIRECTORY "bash-llvm")

set(CPACK_GENERATOR "TGZ")

set(CPACK_DEBIAN_PACKAGE_MAINTAINER "foxmoss@mediaology.com")

include(CPack)
